
exports.seed = function (knex, Promise) {
  // Deletes ALL existing entries
  return knex('card_items').del()
    .then(function () {
      // Inserts seed entries
      return knex('card_items').insert([
        { id: 1, name: 'Bithday Balloons', source: "/images/balloons.jpg", catagory: "birthday" },
        { id: 2, name: 'Birthday Bubbles', source: "/images/bubbles.jpg", catagory: "birthday" },
        { id: 3, name: 'Fuzzy Duck', source: "/images/duck.jpg", catagory: "birthday" },
        { id: 4, name: 'Pink Flowers', source: "/images/flowers.jpg", catagory: "birthday" },
        { id: 5, name: 'Birthday Cake Frog', source: "/images/frog.jpg", catagory: "birthday" },
        { id: 6, name: 'Party Guinea-Pig', source: "/images/guinea_pig.jpg", catagory: "birthday" },
        { id: 7, name: 'Cheerful Birthday', source: "/images/paisley.jpg", catagory: "birthday" },
        { id: 8, name: 'Colorful Ribbons', source: "/images/ribbons.jpg", catagory: "birthday" },
        { id: 9, name: 'Scrabble Lover', source: "/images/scrabble.jpg", catagory: "birthday" },
        { id: 10, name: 'Love Birds', source: "/images/birds.png", catagory: "valentines" },
        { id: 11, name: 'Cloud Valentines', source: "/images/cloud.jpg", catagory: "valentines" },
        { id: 12, name: 'Colorful Valentines', source: "/images/colorful_valentine.jpg", catagory: "valentines" },
        { id: 13, name: 'Cupid Valentnes', source: "/images/happy.png", catagory: "valentines" },
        { id: 14, name: 'Warm Valentines', source: "/images/heart.jpg", catagory: "valentines" },
        { id: 15, name: 'Love You Always', source: "/images/love.jpg", catagory: "valentines" },
        { id: 16, name: 'Valentine Parrot', source: "/images/parrot.jpg", catagory: "valentines" },
        { id: 17, name: 'Tree of Hearts', source: "/images/tree.jpg", catagory: "valentines" },
        { id: 18, name: 'Wood Heart', source: "/images/wood_heart.jpg", catagory: "valentines" },
        { id: 19, name: 'Bunny Dogs', source: "/images/bunny_dogs.jpg", catagory: "easter" },
        { id: 20, name: 'Bunny Ears', source: "/images/bunny_ears.png", catagory: "easter" },
        { id: 21, name: 'Happy Easter', source: "/images/bunny_easter.jpg", catagory: "easter" },
        { id: 22, name: 'Hatching Bunny', source: "/images/bunny_egg.jpg", catagory: "easter" },
        { id: 23, name: 'Ceramic Bunny', source: "/images/bunny.jpg", catagory: "easter" },
        { id: 24, name: 'Butterfly Easter', source: "/images/butterfly.jpg", catagory: "easter" },
        { id: 25, name: 'Chick', source: "/images/chick.jpg", catagory: "easter" },
        { id: 26, name: 'Tulips', source: "/images/tulip_easter.jpg", catagory: "easter" },
        { id: 27, name: 'Grass Easter', source: "/images/happy_easter.jpg", catagory: "easter" },
        { id: 28, name: 'Elephant with Flowers', source: "/images/elephant.jpg", catagory: "get_well" },
        { id: 29, name: 'Flowery Get Well', source: "/images/blue_get_well.jpg", catagory: "get_well" },
        { id: 30, name: 'Teddy with Tissues', source: "/images/cold.jpg", catagory: "get_well" },
        { id: 31, name: 'Monkey and Teddy', source: "/images/cold2.jpg", catagory: "get_well" },
        { id: 32, name: 'Doctor Teddy', source: "/images/doctor.jpg", catagory: "get_well" },
        { id: 33, name: 'Get Well with Leaves', source: "/images/leaf_get_well.jpg", catagory: "get_well" },
        { id: 34, name: 'Smiley Get Well', source: "/images/smiley.jpg", catagory: "get_well" },
        { id: 35, name: 'Band-aid Teddy', source: "/images/teddy.jpg", catagory: "get_well" },
        { id: 36, name: 'Bandaged Teddy', source: "/images/teddy2.jpg", catagory: "get_well" },
        { id: 37, name: 'Blue Christmas', source: "/images/blue_tree.jpg", catagory: "christmas" },
        { id: 38, name: 'Candle Flame', source: "/images/candle.jpg", catagory: "christmas" },
        { id: 39, name: 'Cookie Christmas', source: "/images/merry.jpg", catagory: "christmas" },
        { id: 40, name: 'Purple Christmas', source: "/images/purple_xmas.jpg", catagory: "christmas" },
        { id: 41, name: 'Deer and Bunny', source: "/images/reindeer.jpg", catagory: "christmas" },
        { id: 42, name: 'Rudolph', source: "/images/rudolph.jpg", catagory: "christmas" },
        { id: 43, name: 'Christmas Sweetheart', source: "/images/sweetheart.jpg", catagory: "christmas" },
        { id: 44, name: 'Ho, Ho, Ho', source: "/images/baby.jpg", catagory: "christmas" },
        { id: 45, name: 'Christmas Tree', source: "/images/xmas_tree.jpg", catagory: "christmas" },
        { id: 46, name: 'Cheers', source: "/images/cheers.jpg", catagory: "anniversary" },
        { id: 47, name: 'Coffe Love', source: "/images/coffee.jpg", catagory: "anniversary" },
        { id: 48, name: 'Loving Lions', source: "/images/lion.jpg", catagory: "anniversary" },
        { id: 49, name: 'Monkey Love', source: "/images/monkey.jpg", catagory: "anniversary" },
        { id: 50, name: 'Old Couple', source: "/images/old-couple.jpg", catagory: "anniversary" },
        { id: 51, name: 'Wine Lovers', source: "/images/wine.jpg", catagory: "anniversary" },
        { id: 52, name: 'Anniversary Flowers', source: "/images/frame.png", catagory: "anniversary" },
        { id: 53, name: 'Pink Flowers', source: "/images/flower.jpg", catagory: "anniversary" },
        { id: 54, name: 'Holding Hands', source: "/images/hands.jpg", catagory: "anniversary" },
        { id: 55, name: 'Joined Hands', source: "/images/hands2.jpg", catagory: "wedding" },
        { id: 56, name: 'Dusk Wedding', source: "/images/couple.jpg", catagory: "wedding" },
        { id: 57, name: 'Pink Sneakers', source: "/images/Pink_sneakers.jpg", catagory: "wedding" },
        { id: 58, name: 'Wedding Rings', source: "/images/rings.jpg", catagory: "wedding" },
        { id: 59, name: 'Sunset', source: "/images/sun.jpg", catagory: "wedding" },
        { id: 60, name: 'Sunset Wedding', source: "/images/sunset_wedding.jpg", catagory: "wedding" },
        { id: 61, name: 'Wedding Shoes', source: "/images/wedding-shoes.jpg", catagory: "wedding" },
        { id: 62, name: 'Wedding Trees', source: "/images/wedding_trees.jpg", catagory: "wedding" },
        { id: 63, name: 'Wedding Flowers', source: "/images/wedding_flowers.jpg", catagory: "wedding" },
      ]);
    });
};
